### ISSUE TITLE
[ Core Concepts ] Create the pod that was just described using YAML

### ISSUE THREAD

**Issue by zepouet** [dgkanatsios/CKAD-exercises#12]
Hello,

It seems the namespace is not defined into yaml.
Maybe we could add 

```
kubectl create -f pod.yaml -n mynamespace
```

Thanks a lot !

**Comment by dgkanatsios** [comment]
Thanks for this! Would you like to do a Pull Request to fix that? Would be happy to merge after reviewing :)

**Comment by ZCJ** [comment]
@dgkanatsios I just submitted a pull request for this

**Comment by dgkanatsios** [comment]
Thanks!
