### ISSUE TITLE
The command 'kubectl cp' can not run in the last question in g.state.md

### ISSUE THREAD

**Issue by echang0929** [dgkanatsios/CKAD-exercises#142]
There is an error for the command:
```
kubectl cp busybox:/etc/passwd ./passwd # kubectl cp command
```
I think you need update it to 
```
kubectl cp busybox:etc/passwd ./passwd # kubectl cp command
```

**Comment by dgkanatsios** [comment]
makes sense, do you want to create a PR with it? Thanks!

**Comment by dgkanatsios** [comment]
PR merged, feel free to re-open if the issue persists.

**Comment by ismailyenigul** [comment]
Hi @dgkanatsios it seems PR https://github.com/dgkanatsios/CKAD-exercises/pull/147  is not merged yet

**Comment by dgkanatsios** [comment]
oops, my bad! It should be merged now :)
