### ISSUE TITLE
Explanation required for --expose option

### ISSUE THREAD

**Issue by hiteshsai** [dgkanatsios/CKAD-exercises#155]
In Core concepts, we did not use `--expose`
<img width="896" alt="Screen Shot 2020-11-22 at 13 30 31" src="https://user-images.githubusercontent.com/20929820/99894451-fcb81000-2cc6-11eb-8cc9-2f3a2bc3b074.png">

But in service, we are using `--expose`
<img width="896" alt="Screen Shot 2020-11-22 at 13 30 52" src="https://user-images.githubusercontent.com/20929820/99894450-fa55b600-2cc6-11eb-8b12-d9b9a55b2e4f.png">

I feel explanation bit more explanation is required for the `--expose` option.

**Comment by pantelis-karamolegkos** [comment]
```
▶ k run --help | grep -i expose
  # Start a hazelcast pod and let the container expose port 5701.
      --expose=false: If true, service is created for the container(s) which are run
      --port='': The port that this container exposes.
```

**Comment by hiteshsai** [comment]
@pantelis-karamolegkos I understand. In both the above questions, Expose was asked.
