### ISSUE TITLE
kubectl run is deprecated with deployment generator

### ISSUE THREAD

**Issue by abdennour** [dgkanatsios/CKAD-exercises#16]
[Here](https://github.com/dgkanatsios/CKAD-exercises/blob/master/c.pod_design.md#create-a-deployment-with-image-nginx178-2-replicas-defining-port-80-as-the-port-that-this-container-exposes-dont-create-a-service-for-this-deployment), you put this answer:

```sh
kubectl run nginx --image=nginx:1.7.8 --replicas=2 --port=80
```

Since `kubeclt run` is now deprecated with deployments, this is the alternative:

```sh
kubectl create deployment nginx  --image=nginx:1.7.8  --dry-run -o yaml | sed 's/replicas: 1/replicas: 2/g'  | sed 's/image: nginx:1.7.8/image: nginx:1.7.8\n        ports:\n        - containerPort: 80/g' | kubectl apply -f -
```
Unfortunately, `kubectl create` does not support `--replicas` nor `--port`. That's why the alternative was too long 😁

I will open PR or anyone can open it. 
Thanks!

**Comment by dgkanatsios** [comment]
[Pushed](https://github.com/dgkanatsios/CKAD-exercises/commit/b2784f88ed4902cbc1381f08db802f97abe83288) with info about deprecation and a couple of alternative solutions, including yours. Thank you!
