### ISSUE TITLE
Multi_Container_Pods: Error from server (AlreadyExists): pods "box" already exists

### ISSUE THREAD

**Issue by AydinChavez** [dgkanatsios/CKAD-exercises#161]
In https://github.com/dgkanatsios/CKAD-exercises/blob/master/b.multi_container_pods.md there is a small error in the second question:
```
...
# Execute wget
kubectl run box --image=busybox --restart=Never -it --rm -- /bin/sh -c "wget -O- IP"
...
```

The new pod must have another name than "pod" because "pod" was already started, otherwise you will get a
**Error from server (AlreadyExists): pods "box" already exists**

So instead of
`kubectl run box --image=busybox --restart=Never -it --rm -- /bin/sh -c "wget -O- IP"
`
use something like
`kubectl run box2 --image=busybox --restart=Never -it --rm -- /bin/sh -c "wget -O- IP"
`

**Comment by dgkanatsios** [comment]
I believe this was fixed in #165, let me know if this is not the case!
