### ISSUE TITLE
Multi-container Pods > 2nd exercise > Getting error following the solution provided

### ISSUE THREAD

**Issue by Arboledas** [dgkanatsios/CKAD-exercises#178]
I am following the steps in the 2nd exercise answer and I get on the STATUS column "Init:Error", so I can't finish the exercise.

When I check the logs:
`kubectl logs box`
The output is:
_Error from server (BadRequest): container "nginx" in pod "box" is waiting to start: PodInitializing_

When I describe the pod box:
`kubectl describe pod box`
The output is:
Name:         box
Namespace:    default
Priority:     0
Node:         kubenode-2/10.132.0.4
Start Time:   Wed, 24 Feb 2021 15:07:58 +0000
Labels:       run=box
Annotations:  cni.projectcalico.org/podIP: 192.168.77.91/32
              cni.projectcalico.org/podIPs: 192.168.77.91/32
Status:       Pending
IP:           192.168.77.91
IPs:
  IP:  192.168.77.91
Init Containers:
  box:
    Container ID:  docker://6cdd084115dddc1f66aa397ef83e0770a651516a0ae9f6bca955c6c095c526ed
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:c6b45a95f932202dbb27c31333c4789f45184a744060f6e569cc9d2bf1b9ad6f
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      wget -O /work-dir/index.html http://neverssl.com/online
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 24 Feb 2021 15:11:42 +0000
      Finished:     Wed, 24 Feb 2021 15:12:12 +0000
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bwqjq (ro)
      /work-dir from vol (rw)
Containers:
  nginx:
    Container ID:
    Image:          nginx
    Image ID:
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/share/nginx/html from vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-bwqjq (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  vol:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-bwqjq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-bwqjq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m36s                  default-scheduler  Successfully assigned default/box to kubenode-2
  Normal   Pulled     4m34s                  kubelet            Successfully pulled image "busybox" in 1.622840177s
  Normal   Pulled     4m2s                   kubelet            Successfully pulled image "busybox" in 1.445794935s
  Normal   Pulled     3m15s                  kubelet            Successfully pulled image "busybox" in 1.497044653s
  Normal   Created    2m14s (x4 over 4m33s)  kubelet            Created container box
  Normal   Pulled     2m14s                  kubelet            Successfully pulled image "busybox" in 1.458443236s
  Normal   Started    2m13s (x4 over 4m33s)  kubelet            Started container box
  Warning  BackOff    65s (x7 over 3m31s)    kubelet            Back-off restarting failed container
  Normal   Pulling    54s (x5 over 4m35s)    kubelet            Pulling image "busybox"
  Normal   Pulled     53s                    kubelet            Successfully pulled image "busybox" in 1.461627372s

**Comment by girdhar-singh-rathore** [comment]
I assume you forget to put --restart=Never thats the reason it is back-off

**Comment by Arboledas** [comment]
> I assume you forget to put --restart=Never thats the reason it is back-off

I've tried with --restart=Never and it throws the same error: 

`Error from server (BadRequest): container "nginx" in pod "box" is waiting to start: PodInitializing`

**Comment by Arboledas** [comment]
I switched from Calico to Flannel network and it works perfectly.
