### ISSUE TITLE
Using args

### ISSUE THREAD

**Issue by arezk84** [dgkanatsios/CKAD-exercises#196]
In multi-container pod example: https://github.com/dgkanatsios/CKAD-exercises/blob/master/b.multi_container_pods.md

Why don't we use `command` in the init container instead of `args`?

As k8s docs: 
> If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.

**Comment by jhchong92** [comment]
In this example, `command` and `args` can be used interchangeably. 

The situation where `command` can yield different results is when the Docker image uses `ENTRYPOINT`. And using `command` will overwrite the `ENTRYPOINT` as stated in the docs:-

`kubectl explain pod.spec.containers.command`
> ... The docker image's
     ENTRYPOINT is used if this is not provided. 

In this [article](https://itnext.io/practical-tips-for-passing-ckad-exam-6cbdf2d35cb1), you may find some info on the topic. Also, the author wrote a [gist](https://gist.github.com/sensei-wu/bc853aba775fa5ddedd1e24d08ddd768) demonstrating the difference between `CMD` and `ENTRYPOINT` in Docker, which relates to this topic as well.
