### ISSUE TITLE
CronJob param activeDeadlineSeconds vs startingDeadlineSeconds

### ISSUE THREAD

**Issue by serbande** [dgkanatsios/CKAD-exercises#201]
I think the solution of the exercise https://github.com/dgkanatsios/CKAD-exercises/blob/master/c.pod_design.md#create-a-cron-job-with-image-busybox-that-runs-every-minute-and-writes-date-echo-hello-from-the-kubernetes-cluster-to-standard-output-the-cron-job-should-be-terminated-if-it-takes-more-than-17-seconds-to-start-execution-after-its-schedule should use CronJob.spec.startingDeadlineSeconds instead of cronjob.spec.jobTemplate.spec.activeDeadlineSeconds, as we are requested to put a deadline between scheduling and job start and not to a deadline for job execution time.

**Comment by dgkanatsios** [comment]
thanks! Feel free to make a Pull Request with the suggestion :)

**Comment by dgkanatsios** [comment]
Fixed on #219, feel free to re-open if there is an issue. Thanks!
