### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amerello** [dgkanatsios/CKAD-exercises#21]
Would you say that if you're able to solve this problems within a reasonable time, you are well prepared for the CKAD?

**Comment by dgkanatsios** [comment]
These exercises helped me prepare and pass, so, at least for me, it worked! I'd say you need to repeat them multiple times so you can be really fast, time is of the essence during the exam.

**Comment by amerello** [comment]
Nice, thank you for preparing these sheets!
