### ISSUE TITLE
[Help] Canary Deployment question

### ISSUE THREAD

**Issue by jolly701** [dgkanatsios/CKAD-exercises#244]
Modify the Deployments so that:
1. a maximum number of 8 pods run in the `test` namespace
2. 20% of the krill-service's traffic goes to the `canary-krill-deployment` Pods
![image](https://user-images.githubusercontent.com/98242294/150661854-3a03d7d2-7e29-4fcb-858a-358a63403aa9.png)

**Comment by bavlayan** [comment]
Hi,
I took CKAD exam twice. I faced similar face question in all of them. Actually, solution is quite simple. 
There are two things that you should do.
1) Scale current-krill-deployment to 6 pods with `kubectl scale deployment current-krill-deployment --replicas=6`
2) Create deployment canary-krill-deployment or scale it. In the exam, I created the deployment with given yaml file. 
   ->  `kubectl scale deployment canary-krill-deployment --replicas=2`
   -> Set replicas count to 2 in given yaml file.

**Comment by jolly701** [comment]
Thanks @bavlayan would you please explain a little bit more? I thought it is resource quote related oR something

**Comment by janekmichalik** [comment]
@jolly701 it is related to new CKAD curriculum updates (blue/green and canary deployments)

1. Total amount of pods: 8
2. canary-krill-deployment: 20% which is 0.2 x 8 ~= 2 
3. It gives us: current-krill-deployment: 6
4. Scale each deployment to to the calculated value



Canary deployment gives us a possibility to deploy two versions of the same deployment, so the traffic is being split accordingly. The client is not affected as the service is working, but from the backend perspective - we are able to see how the new version behaves.

**Comment by bavlayan** [comment]
> Thanks @bavlayan would you please explain a little bit more? I thought it is resource quote related oR something

It is not related to resource quote or something. This question is just related to how you can scale deployment. You can only play on amount of pods of deployment. @janekmichalik explains it well

**Comment by jolly701** [comment]
Well, I overestimated the complexity of the question. Thank you so much @bavlayan @janekmichalik 
I just attended the CKAD exam and I have a few more questions that I think I didn't work out
_____________________________________________________________________________________
1. A pod within the deployment named deployment-xyz and in the namespace ns-123 is logging errors.
And the error looks like "cannot list resource serviceaccounts in the namespace ns-123"
You need to update the deployment to resolve the errors
Given the yaml file of the deployment-xyz
_____________________________________________________________________________________

2. Modify the existing deployment named foo, running in namespace bar, so that its containers
-  run with user ID 1000
- privilege escalation is forbidden

Given the yaml file of the deployment-xyz
_____________________________________________________________________________________

3. There's a pod named `newpod` and you need to allow it to communicate with the `API` and `Storage` pods but nothing else. Edit the `newpod` to use a network policy that will allow it to send and receive traffic only to and from the `API` and `Stoage` pods. There are three nerwork policy there already, `access-api`, `access-storage`, and `access-all`. You shold not create, modify or delete any network polices while completing this.

**Comment by janekmichalik** [comment]
@jolly701 

1. As you are not able to verbs some kind of resources, it means that related `Role/ClusterRole` does not allow you to.
The process with connecting` Role/ClusterRole` with the dedicated `Pod` is as follows: `Role/ClusterRole -> RoleBinding/ClusterRoleBinding -> ServiceAccount -> Pod`. As you are asked to change the deployment only it means that your changes will be related to `ServiceAccount` within the deployment. I have deleted the `serviceAccountName` field from the deployment, so the deployment used the default one, which has proper permissions.

2. It is related to Security Context. All you have to do is to add (at the container level):
      ```
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
      ```

3. It is related to Network Policy. There was also an `access-deny` network policy as well. I do not know, if I have done it correctly, but the only thing I had done, was to add the label (I do not remember the label, but it was provided in `access-api` and `access-storage` NetwokPolicies) to the `newpod`. And after that, the storage and api pods, will be able to communicate only with the `newpod` (bi-directional communication) as `access-deny` blocks everything else. But not sure about this one.

**Comment by jolly701** [comment]
A million thanks for the detailed answer @janekmichalik It really helps
