### ISSUE TITLE
[Help] OCI-compliant container

### ISSUE THREAD

**Issue by roger71818** [dgkanatsios/CKAD-exercises#245]
I'm a newbie of Docker and met a docker question 
1. Write a Dockerfile that creates a image with the following spec
- use nginx as base image
- adds the following files to /user/share/nginx/:
   - ~/student/text1.html
   - ~/student/text2.html
- Overwrites `/user/share/nginx/index.html` with `~/student/text2.html`

2. Using the created Dockerfile and build an OCI-compliant container image

**Comment by janekmichalik** [comment]
@roger71818 please get acquainted with Docker basis…


1. Navigate to `student` directory.
2. Run command: `vi Dockerfile`
3. Fill the Dockerfile with below content:
 ```
FROM nginx

COPY text1.html /user/share/nginx/
COPY text2.html /user/share/nginx/index.html

```
4. Run command: `docker build . -t docker:newbie `
