### ISSUE TITLE
Logging - invalid command

### ISSUE THREAD

**Issue by dgofman** [dgkanatsios/CKAD-exercises#293]
URL:

https://github.com/dgkanatsios/CKAD-exercises/blob/main/e.observability.md#create-a-busybox-pod-that-runs-i0-while-true-do-echo-i-date-ii1-sleep-1-done-check-its-logs

Task:

Create a busybox pod that runs 'i=0; while true; do echo "$i: ((i+1)); sleep 1; done'. Check its logs

Should be:

Create a busybox pod that runs 'i=0; while true; do echo "$i: **$(date)";** i=$((i+1)); sleep 1; done'.  Check its logs

Unable to copy **$(date)\";**

**Comment by dgkanatsios** [comment]
sorry, catching up on this - is this still an issue? if it is, please open a PR. thanks!
