### ISSUE TITLE
missing tag

### ISSUE THREAD

**Issue by RafalMaleska** [dgkanatsios/CKAD-exercises#32]
i dosent work like this: "--image=dgkanatsios/simpleapp"

the tag is missing: "--image=dgkanatsios/simpleapp:2.0"

**Comment by dgkanatsios** [comment]
I actually did some changes on the simpleapp image on Docker Hub and the `latest` tag was removed, sorry for that! I just re-added it, can you please try again with `--image=dgkanatsios/simpleapp`?

**Comment by dgkanatsios** [comment]
ping @RafalMaleska

**Comment by RafalMaleska** [comment]
Hi! 

Works fine for me. With latest and 2.0 

Used --image=dgkanatsios/simpleapp:2.0
