### ISSUE TITLE
second pod not always on first pod's node in pv/pvc example

### ISSUE THREAD

**Issue by tmoeller328** [dgkanatsios/CKAD-exercises#49]
I don't have rights to submit a new branch and PR to your repo, so here are the details:

### Create a second pod (deployed to the same node the first pod is on) which is identical with the one you just created (you can easily do it by changing the 'name' property on pod.yaml). Connect to it and verify that '/etc/foo' contains the 'passwd' file. Delete pods to cleanup

<details><summary>show</summary>
<p>

Create the second pod, called busybox2:

```bash
# get details about the first pod
# take the node name from the 7th column
# remove the title/header line
# add a label to that node
kubectl get pods busybox -o wide | awk '{print $7}' | grep -v NODE | xargs -I{} kubectl label node {} use=thisone
vim pod.yaml
# change 'metadata.name: busybox' to 'metadata.name: busybox2'
# add a nodeSelector with the same label as the node to the yaml
kubectl create -f pod.yaml
kubectl exec busybox2 -- ls /etc/foo # will show 'passwd'
# cleanup
kubectl delete po busybox busybox2
```

**Comment by dgkanatsios** [comment]
thank you!
that's right, you cannot create a new branch here, the way that you can do a Pull Request is by
- forking this project
- creating a new branch
- do your changes
- finally, from your branch do a PR towards this repo's master

check the instructions here and let me know if something is not working for you -> https://help.github.com/en/articles/creating-a-pull-request

**Comment by tmoeller328** [comment]
Sorry, yeah never have had opportunity to do PR from fork yet.  Thx for your exercises, these are awesome learning tools!
