### ISSUE TITLE
--rm flag giving error

### ISSUE THREAD

**Issue by parth-pandit** [dgkanatsios/CKAD-exercises#61]
I am getting below error when I pass `--rm` flag as shown in the solution for 3rd questions of Services and Networking section.

`error: --rm should only be used for attached containers`. 

Any idea why?

**Comment by parth-pandit** [comment]
Here is the output of my `kubectl version` command.

`
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`

**Comment by dgkanatsios** [comment]
Not sure why this is not working for you. Can you check the command again? This is what I see

```bash
dgkanatsios@digkanat:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
dgkanatsios@digkanat:~$ kubectl run busybox --rm --image=busybox -it --restart=Never -- sh
If you don't see a command prompt, try pressing enter.
/ # uname -a
Linux busybox 4.15.0-1055-azure #60-Ubuntu SMP Thu Aug 8 18:29:07 UTC 2019 x86_64 GNU/Linux
/ # exit
pod "busybox" deleted
```

**Comment by runlevl4** [comment]
Are you including the `-it` flags? You need to use `--rm -it` together or you'll get the error you describe.

**Comment by parth-pandit** [comment]
This makes sense! I did not use -it with —rm. I will try again.

Regards,
Parth Pandit
Sr. Platform Architect - Pivotal Cloud Foundry
http://www.linkedin.com/in/parthpandit
Phone: +1 (470) 422-6629
________________________________

**Comment by parth-pandit** [comment]
> Are you including the `-it` flags? You need to use `--rm -it` together or you'll get the error you describe.

Yes.. that was the catch! Thanks. It works after putting '-it'.

**Comment by ypresto** [comment]
Without `--attach'` or `-i`/`--stdin`, kubectl run will show `pod xxx is created` message then exit immediately, so there is no chance to delete pod after its exit (as kubectl does not wait for exit).
