### ISSUE TITLE
describe command doesn't support -o jsonpath

### ISSUE THREAD

**Issue by edodiazv** [dgkanatsios/CKAD-exercises#75]
https://github.com/dgkanatsios/CKAD-exercises/blob/master/c.pod_design.md#check-the-annotations-for-pod-nginx1

> As an alternative to using | grep you can use jsonPath like -o jsonpath='{.metadata.annotations}{"\n"}'

:)

**Comment by velmuruganvelayutham** [comment]
k get pods -o jsonpath='{range .items[*]} {.metadata.annotations} {"\n"} {end}'
