### ISSUE TITLE
How close can I expect this from the actual exam?

### ISSUE THREAD

**Issue by ge90toga** [dgkanatsios/CKAD-exercises#84]
Hi, I am preparing CKAD and I think it is great to have this repo to learn and practice but I still would like to know what I should expect from actual exam. Thanks!

**Comment by Jeskz0rd** [comment]
Hi @ge90toga , 

I successfully did both exams, CKA/CKAD, 2 weeks ago and I used the exercises here to practice.

As far as you can complete **all the questions** here you'll be able to take the exam. The less you need to access the kubernetes docs the better, as you can lose precious time while searching for yaml definitions and samples in the docs. Try to read [kubernetes documentation](https://kubernetes.io/docs/home/) based on the exam topics and also **do EVERY kubernetes** [TASK](https://kubernetes.io/docs/tasks/) in the docs. 

[This resource] also helped me a lot, even though most of the tasks on it are also presented in this repo. Believe me, do these exercises more than once, read carefully and understand the questions... if it is asking for a POD do not create a deployment. It will be fine :)

Good luck! :+1:
