### ISSUE TITLE
This solution isn't working (or is it just me?)

### ISSUE THREAD

**Issue by gauravpatel2016** [dgkanatsios/CKAD-exercises#95]
I followed all the steps in this exercise https://github.com/dgkanatsios/CKAD-exercises/blob/master/f.services.md#create-an-nginx-deployment-of-2-replicas-expose-it-via-a-clusterip-service-on-port-80-create-a-networkpolicy-so-that-only-pods-with-labels-access-granted-can-access-the-deployment-and-apply-it

But for some reason busybox pod without label is still able to access Nginx service. i am not sure what is the issue.
`kubectl run busybox --image=busybox --rm -it --restart=Never -- wget -O- http://nginx:80 --timeout 2  ` 
should timeout  but I get index.html fine

Thanks

**Comment by gauravpatel2016** [comment]
I did it in mac docker-desktop

**Comment by gauravpatel2016** [comment]
I found the reason.

**Comment by dgkanatsios** [comment]
Thanks @gauravpatel2016. Can you mention what happened, just in case it happens to somebody else?

**Comment by gauravpatel2016** [comment]
To apply network policy, you must have networking solution installed like flannel. Locally and katakoda, they were not installed. I tried where networking solution was installed. and It worked fine after that.
